logging:
  level:
    com.rhabad.tutorial: DEBUG

server.error.include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

miURL:
  database: "https://midatabase.com"